#include "obj_fallS.h"

s32 padD70AD0[] = { 0x00000000, 0x00000000 };
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallS_v.vtx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallS_grpAT_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallS_grpBT_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallS_grpDT_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallS_grpCT_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallS_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallCA1_tex_rgb_ia8.ia8.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallA2_tex_rgb_i4.i4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallA3_tex_rgb_i4.i4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallC2_tex_rgb_i4.i4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallC3_tex_rgb_i4.i4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallS_evw_anime_1.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallS_evw_anime_2.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallS_evw_anime_3.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallS_evw_anime_4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallS/obj_fallS_evw_anime.inc.c"
