#include "obj_house.h"

s32 padD81BB0[] = { 0x00000000, 0x00000000 };
#include "assets/jp/objects/object_00D5E000/obj_house/obj_s_house1_v.vtx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/obj_s_house1_window_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/obj_s_house1_light_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/obj_s_house1_t4_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/obj_s_house1_t3_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/obj_s_house1_t2_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/obj_s_house1_t1_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/obj_s_house1_door_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/obj_s_house1_t1_tex_txt.ci4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/obj_s_house1_window_txt.i4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/obj_s_house1_t3_tex_txt.ci4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/obj_s_house1_t2_tex_txt.ci4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/obj_s_house1_t4_tex_txt.ci4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/cKF_je_r_obj_s_house1_tbl.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/cKF_bs_r_obj_s_house1.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/cKF_ckcb_r_obj_s_house1_tbl.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/cKF_kn_obj_s_house1_tbl.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/cKF_c_obj_s_house1_tbl.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/cKF_ds_obj_s_house1_tbl.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/cKF_ba_r_obj_s_house1.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/cKF_ckcb_r_obj_s_house1_out_tbl.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/cKF_kn_obj_s_house1_out_tbl.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/cKF_c_obj_s_house1_out_tbl.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/cKF_ds_obj_s_house1_out_tbl.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_house/cKF_ba_r_obj_s_house1_out.inc.c"
