#include "obj_fallSE.h"

s32 padD71A60[] = { 0x00000000, 0x00000000 };
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallSE_v.vtx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallSE_grpAT_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallSE_grpBT_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallSE_grpDT_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallSE_grpCT_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallSESW_model.gfx.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallCA1_tex_rgb_ia8_2.ia8.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallA2_tex_rgb_i4_2.i4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallA3_tex_rgb_i4_2.i4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallC2_tex_rgb_i4_2.i4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallC3_tex_rgb_i4_2.i4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallSE_evw_anime_1.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallSE_evw_anime_2.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallSE_evw_anime_3.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallSE_evw_anime_4.inc.c"
#include "assets/jp/objects/object_00D5E000/obj_fallSE/obj_fallSE_evw_anime.inc.c"
