#include "tol_tamaire.h"

#include "assets/jp/objects/tol_tamaire/tol_tamaire_v.vtx.inc.c"
#include "assets/jp/objects/tol_tamaire/tol_tamaire_model.gfx.inc.c"
#include "assets/jp/objects/tol_tamaire/tol_tamaire_pal.palette.inc.c"
#include "assets/jp/objects/tol_tamaire/tol_tamaire_r1_tex.ci4.inc.c"
#include "assets/jp/objects/tol_tamaire/tol_tamaire_r2_tex.ci4.inc.c"
#include "assets/jp/objects/tol_tamaire/tol_tamaire_r3_tex.ci4.inc.c"
#include "assets/jp/objects/tol_tamaire/tol_tamaire_w1_tex.ci4.inc.c"
#include "assets/jp/objects/tol_tamaire/tol_tamaire_w2_tex.ci4.inc.c"
#include "assets/jp/objects/tol_tamaire/tol_tamaire_w3_tex.ci4.inc.c"
